apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
  # Ubah argocd-server Service menjadi NodePort
  - path: argocd-server-nodeport.yaml

  # Pin semua Deployment ArgoCD ke node pool "general"
  - path: patch-node-general.yaml
    target:
      kind: Deployment
      namespace: argocd

  # Pin StatefulSet (argocd-application-controller) ke node pool "general"
  - path: patch-node-general.yaml
    target:
      kind: StatefulSet
      namespace: argocd
